<html>
<link rel="stylesheet" href="looks.css">
<head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>About Us | K-Store</title><meta name="author" content="K-Store"/><meta property="og:url" content="https://kstore.ml/about-us"/>
<meta property="og:site_name" content="K-Store"/>
<meta property="og:title" content="Welcome to K-Store"/>
<meta property="og:type" content="website"/>
<meta property="og:image" content="http://img1.wsimg.com/isteam/ip/eb5bd203-fd4d-4af0-9f2e-4fc8f1ca8f86/fcb446b8-e113-45c5-9bbe-524f33c48c7b.jpg"/>
<meta property="og:locale" content="en_IN"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="K-Store"/>
<meta name="twitter:description" content="Welcome to K-Store"/>
<meta name="twitter:image" content="http://img1.wsimg.com/isteam/ip/eb5bd203-fd4d-4af0-9f2e-4fc8f1ca8f86/fcb446b8-e113-45c5-9bbe-524f33c48c7b.jpg"/>
<meta name="twitter:image:alt" content="K-Store"/>

<body>
<div data-ux="Block" class="x-el x-el-div px_-position-relative px_-min-height-250px px_-ff-Quicksand__sans-serif px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><div data-ux="Block" data-route="/" class="x-el x-el-div px_-position-relative px_-ff-Quicksand__sans-serif px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux x-d-route"><div data-ux="Block" class="x-el x-el-div px_-position-relative px_-ff-Quicksand__sans-serif px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><div data-ux="Block" class="x-el x-el-div px_-ff-Quicksand__sans-serif px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><div data-ux="Grid" class="x-el x-el-div px_-d-flex px_-box-sizing-border-box px_-flex-direction-row px_-flex-wrap-wrap px_-m-0_-10px_-20px px_-ff-Quicksand__sans-serif px_-fs-18 _smpx_-m-0_-20px_-40px _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><div data-ux="GridCell" class="x-el x-el-div px_-box-sizing-border-box px_-flex-grow-1 px_-flex-shrink-1 px_-flex-basis-100P px_-p-0_10px_20px px_-max-width-100P px_-text-align-center px_-ff-Quicksand__sans-serif px_-fs-18 _smpx_-p-0_20px_40px _smpx_-ml-16p666666666666664P _smpx_-flex-basis-66p66666666666666P _smpx_-max-width-66p66666666666666P _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"></div></div></div></div></div></div></div></div></div></section></div>
<br><br><br>

<div id="f711c1b3-cb5c-4004-bc41-3a8c9c68b646" class="widget widget-footer widget-footer-footer-1"><section data-ux="Section" class="x-el x-el-section px_-bc-rgb22__22__22 px_-pt-60px px_-pb-60px px_-ff-_Sofia___cursive px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><div data-ux="Container" class="x-el x-el-div px_-ml-auto px_-mr-auto px_-pl-20px px_-pr-20px px_-max-width-100P px_-ff-_Sofia___cursive px_-fs-18 _smpx_-w-728px _mdpx_-w-984px _mdpx_-fs-18 _lgpx_-w-1160px _lgpx_-fs-18 x-d-ux"><div data-ux="Layout" class="x-el x-el-div px_-text-align-center px_-ff-_Sofia___cursive px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><h5 data-ux="Heading" data-aid="FOOTER_COPYRIGHT_RENDERED" data-route="copyright" class="x-el x-el-h5 px_-overflow-wrap-break-word px_-word-wrap-break-word px_-word-break-break-word px_-fs-18 px_-c-rgb247__247__247 px_-fw-400 px_-lh-1p25 px_-ml-0 px_-mr-0 px_-mt-0 px_-mb-20px px_-ff-Quicksand__sans-serif _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux x-d-aid x-d-route x-rt"><span style="margin:0px;">Copyright © 2018 K-Store - All Rights Reserved. <span class="x-el x-el-span px_-fs-unset px_-ff-Quicksand__sans-serif px_-fw-700 x-d-ux">&nbsp;</span><a href="http://97522b42.orson.website/" class="x-el x-el-a px_-overflow-wrap-break-word px_-fs-18 px_-fw-400 px_-c-rgb113__128__239 px_-text-decoration-none px_-d-inline px_-cursor-pointer px_-ff-Quicksand__sans-serif px__hover-c-rgb130__143__241 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"><span class="x-el x-el-span px_-fs-unset px_-ff-Quicksand__sans-serif px_-fw-700 x-d-ux">K-Wallet</span></a><span class="x-el x-el-span px_-fs-unset px_-ff-Quicksand__sans-serif px_-fw-700 x-d-ux">&nbsp;</span></span></h5><hr data-ux="HR" class="x-el x-el-hr px_-border-color-rgb42__42__42 px_-border-bottom-width-1px px_-border-style-solid px_-mt-0 px_-mb-20px px_-w-50px px_-ml-auto px_-mr-auto px_-ff-_Sofia___cursive px_-fs-18 _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux"/><h5 data-ux="Heading" data-aid="FOOTER_POWERED_BY_RENDERED" data-route="poweredBy" class="x-el x-el-h5 px_-overflow-wrap-break-word px_-word-wrap-break-word px_-word-break-break-word px_-fs-18 px_-c-rgb137__137__137 px_-fw-400 px_-lh-1p25 px_-ml-0 px_-mr-0 px_-mt-0 px_-mb-0 px_-ff-Quicksand__sans-serif _mdpx_-fs-18 _lgpx_-fs-18 x-d-ux x-d-aid x-d-route"><span>Powered by K-Wallet.</span></h5></div></div></section></div></span></div>
</body>
</html>